###
GET http://localhost:8080/users/1
###
GET http://localhost:8080/users/1/board

###
GET http://localhost:8080/jobs?page=1&limit=5

###
GET http://localhost:8080/jobs?page=1&limit=5&filterDate=05-15-2022
